branches:
  only:
    - master

language: ruby
rvm:
  - "2.7.0"
  - "2.7.1"

install: 
  - bundle install
script: 
  - bundle exec rspec spec
  - CODECLIMATE_REPO_TOKEN=${CODECLIMATE_LAB42CONSOLE_TOKEN} bundle exec codeclimate-test-reporter
